### ISSUE TITLE
no applicable method for 'as.tbl_json' applied to an object of class "response"

### ISSUE THREAD

**Issue by smithjd** [sailthru/tidyjson#49]
Setup:

``` library(httr)
library(lubridate)
library(jsonlite)
library(dplyr)
library(tidyjson)

options(stringsAsFactors = FALSE)

meetup_api <- Sys.getenv("meetup_api")
```

Extract data (R log):

> page_num = 0
> url_page <- paste("&offset = ", page_num)
> url_group_start <- paste0("https://api.meetup.com/find/groups?sign=true&photo-host=public&key=", meetup_api)
> url_query <- "&zip=97206&radius=3&category=34&page=200"
> tech_sample <- GET(url = paste0(url_group_start,url_query,url_page))
> tech_sample$status_code
> [1] 200
> n_groups <- as.numeric(tech_sample$headers$`x-total-count`)
> n_groups
> [1] 36
> typeof(tech_sample)
> [1] "list"
> 
> (n_groups <- as.numeric(tech_sample$headers$`x-total-count`))
> [1] 36
> tech_sample <- tech_sample %>% as.tbl_json()
> Error in UseMethod("as.tbl_json") : 
>   no applicable method for 'as.tbl_json' applied to an object of class "response"

Am I just mis-using or mis-understanding the package?

**Comment by vats-div** [comment]
Looks like as.tbl_json can not be applied to lists.

I'm not sure what are the contents of `tech_sample`, but this may work:

`as.character(tech_sample) %>% as.tbl_json`

For example, the following works:

```
> tech_sample <- list(a = 1, b = '{"a": 1}', c = "2", d = 5)
> tech_sample %>% as.character %>% as.tbl_json %>% json_types
  document.id   type
1           1 number
2           2 object
3           3 number
4           4 number
```

**Comment by smithjd** [comment]
There must be some difference between the JSON that I'm retrieving from the meetup api and the examples in the [vignette](https://cran.r-project.org/web/packages/tidyjson/vignettes/introduction-to-tidyjson.html) that I'm working through.  I'm finding it difficult to document this problem because a query needs to provide credential (e.g., a password equivalent).  Here is the table that I'm working with, in case you could look at it:
[tech_sample.Rdata.zip](https://github.com/sailthru/tidyjson/files/52531/tech_sample.Rdata.zip)

**Comment by smithjd** [comment]
This issue resolves when the following code is used to pull the JSON from an API like Meetup's:

```
raw_contents <- GET(url = url)  
json_raw <- httr::content(raw_contents, type = "text")
```
